uicc0 = {
    imsi = "208950000000031";
    key  = "0C0A34601D4F07677303652C0462535B";
    opc  = "63bfa50ee6523365ff14c1f45f88737d";
    dnn  = "default";
    nssai_sst = 1;
    nssai_sd  = 0x1;
}

plmn_list = (
    {
      mcc = 208;
      mnc = 95;
      mnc_length = 2;
    }
);

//Define the list of required slices (Requested NSSAIs)
snssaiList = (
    { sst = 1; sd = 0x1; dnn = "default"; },
    { sst = 2; sd = 0x2; dnn = "oai"; }
);
	
pduSessions = (
    {
        id = 10;
        sst = 1;
        sd = 0x1;
        dnn = "default";
        type = "IPV4";
    },
    {
        id = 11;
        sst = 2;
        sd = 0x2;
        dnn = "oai";
        type = "IPV4";
    }
);

position0 = {
    x = 0.0;
    y = 0.0;
    z = 6377900.0;
}

@include "channelmod_rfsimu_LEO_satellite.conf"
